// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AuthenticationRequest struct {
	Token     string `header:"Token,optional"`     //放在header里面，可选
	ValidPath string `header:"ValidPath,optional"` //请求url
}

type AuthenticationResponse struct {
	Code   int    `json:"code"`
	Msg    string `json:"msg"`
	UserId uint   `json:"user_id"` //用户id
	Role   uint   `json:"role"`    //角色
}

type LoginInfo struct {
	Token string `json:"token"`
}

type LoginRequest struct {
	UserName string `json:"user_name"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Code int       `json:"code"`
	Msg  string    `json:"msg"`
	Data LoginInfo `json:"data"`
}

type OpenLoginInfo struct {
	Name string `json:"name"`
	Icon string `json:"icon"`
	Href string `json:"href"`
}

type OpenLoginResponse struct {
	Code int             `json:"code"`
	Msg  string          `json:"msg"`
	Data []OpenLoginInfo `json:"data"`
}

type RegisterRequest struct {
	UserName string `json:"user_name"`
	Password string `json:"password"`
}

type Response struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
	Data string `json:"data"`
}
