// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type ApplyFriendRequest struct {
	UserID uint `json:"uid"` //添加好友的用户id
}

type ApplyFriendResponse struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
	Data bool   `json:"data"`
}

type FriendApplyItem struct {
	FriendVerifyModelId int8   `json:"friend_verify_model_id"`
	UserID              uint   `json:"uid"`
	Nickname            string `json:"nickname"`
	Avatar              string `json:"avatar"`
	Role                int8   `json:"role"`
}

type FriendApplyListRequest struct {
}

type FriendApplyListResponse struct {
	Code int               `json:"code"`
	Msg  string            `json:"msg"`
	List []FriendApplyItem `json:"list"`
}

type FriendDeleteRequest struct {
	UserID uint `json:"uid"`
}

type FriendDeleteResponse struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
	Data bool   `json:"data"`
}

type FriendInfoRequest struct {
	UserID uint `header:"uid"`
	Role   int8 `header:"role"` //这个地方支持 header、path、form
}

type FriendInfoResponse struct {
	Code int          `json:"code"`
	Msg  string       `json:"msg"`
	Data UserInfoData `json:"data"`
}

type FriendListRequest struct {
	UserID uint `header:"uid"`
	Role   int8 `header:"role"`
	Page   int  `form:"page,optional"`
	Limit  int  `form:"limit,optional"`
}

type FriendListResponse struct {
	List  []UserInfoData `json:"list"`
	Count int            `json:"count"`
}

type Response struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
	Data string `json:"data"`
}

type ResponseFriendApplyRequest struct {
	Friend_verify_id int  `json:"code"`
	Status           int8 `json:"status"` // 1:同意 2:拒绝
}

type ResponseFriendApplyResponse struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
	Data bool   `json:"data"`
}

type UserInfoData struct {
	UserID       uint   `json:"uid"`
	Nickname     string `json:"nickname"`
	Avatar       string `json:"avatar"`
	Role         int8   `json:"role"`
	Abstract     string `json:"abstract"`
	Verification int    `json:"verification"`
}

type UserInfoRequest struct {
	UserID uint `header:"uid"`
	Role   int8 `header:"role"`
}

type UserInfoResponse struct {
	Code int          `json:"code"`
	Msg  string       `json:"msg"`
	Data UserInfoData `json:"data"`
}

type UserInfoUpdateRequest struct {
	Nickname string `json:"nickname,optional"`
	Avatar   string `json:"avatar,optional"`
	Abstract string `json:"abstract,optional"`
}

type UserInfoUpdateResponse struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
	Data bool   `json:"data"`
}

type UserListResponse struct {
	List  []UserInfoData `json:"list"`
	Count int            `json:"count"`
}

type UserSearchRequest struct {
	UserID   uint   `form:"uid"`
	Nickname string `form:"nickname"`
}
