// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type FriendInfoRequest struct {
	UserID uint `header:"uid"`
	Role   int8 `header:"role"` //这个地方支持 header、path、form
}

type FriendInfoResponse struct {
	Code int            `json:"code"`
	Msg  string         `json:"msg"`
	Data []UserInfoData `json:"data"`
}

type FriendListRequest struct {
	UserID uint `header:"uid"`
	Role   int8 `header:"role"`
	Page   int  `form:"page,optional"`
	Limit  int  `form:"limit,optional"`
}

type FriendListResponse struct {
	List  []FriendInfoResponse `json:"list"`
	Count int                  `json:"count"`
}

type Response struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
	Data string `json:"data"`
}

type UserInfoData struct {
	UserID   uint   `json:"uid"`
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
	Role     int8   `json:"role"`
	Abstract string `json:"abstract"`
}

type UserInfoRequest struct {
	UserID uint `header:"uid"`
	Role   int8 `header:"role"`
}

type UserInfoResponse struct {
	Code int          `json:"code"`
	Msg  string       `json:"msg"`
	Data UserInfoData `json:"data"`
}

type UserInfoUpdateRequest struct {
	Nickname string `json:"nickname,optional"`
	Avatar   string `json:"avatar,optional"`
	Abstract string `json:"abstract,optional"`
}

type UserInfoUpdateResponse struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
	Data bool   `json:"data"`
}
