// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type ImageRequest struct {
}

type ImageResponsse struct {
	Url string `json:"url"` //图片地址
}

type ImageShowRequest struct {
}

type ImageShowResponse struct {
}

type Response struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
	Data string `json:"data"`
}
