// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user_rpc.proto

package user

import (
	"context"

	"im-server/im_user/user_rpc/types/user_rpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetUserBatchRequest  = user_rpc.GetUserBatchRequest
	GetUserBatchResponse = user_rpc.GetUserBatchResponse
	GetUserRequest       = user_rpc.GetUserRequest
	GetUserResponse      = user_rpc.GetUserResponse
	UserCreateRequest    = user_rpc.UserCreateRequest
	UserCreateResponse   = user_rpc.UserCreateResponse

	User interface {
		CreateUser(ctx context.Context, in *UserCreateRequest, opts ...grpc.CallOption) (*UserCreateResponse, error)
		GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
		GetUserBatch(ctx context.Context, in *GetUserBatchRequest, opts ...grpc.CallOption) (*GetUserBatchResponse, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) CreateUser(ctx context.Context, in *UserCreateRequest, opts ...grpc.CallOption) (*UserCreateResponse, error) {
	client := user_rpc.NewUserClient(m.cli.Conn())
	return client.CreateUser(ctx, in, opts...)
}

func (m *defaultUser) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	client := user_rpc.NewUserClient(m.cli.Conn())
	return client.GetUser(ctx, in, opts...)
}

func (m *defaultUser) GetUserBatch(ctx context.Context, in *GetUserBatchRequest, opts ...grpc.CallOption) (*GetUserBatchResponse, error) {
	client := user_rpc.NewUserClient(m.cli.Conn())
	return client.GetUserBatch(ctx, in, opts...)
}
