// goctl rpc protoc user_rpc.proto --go_out=./types --go-grpc_out=./types --zrpc_out=.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.20.3
// source: user_rpc.proto

package user_rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NickName      string                 `protobuf:"bytes,1,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Role          int32                  `protobuf:"varint,3,opt,name=role,proto3" json:"role,omitempty"`
	Avator        string                 `protobuf:"bytes,4,opt,name=avator,proto3" json:"avator,omitempty"`
	OpenId        string                 `protobuf:"bytes,5,opt,name=open_id,json=openId,proto3" json:"open_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCreateRequest) Reset() {
	*x = UserCreateRequest{}
	mi := &file_user_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCreateRequest) ProtoMessage() {}

func (x *UserCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCreateRequest.ProtoReflect.Descriptor instead.
func (*UserCreateRequest) Descriptor() ([]byte, []int) {
	return file_user_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *UserCreateRequest) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *UserCreateRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserCreateRequest) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *UserCreateRequest) GetAvator() string {
	if x != nil {
		return x.Avator
	}
	return ""
}

func (x *UserCreateRequest) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

type UserCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCreateResponse) Reset() {
	*x = UserCreateResponse{}
	mi := &file_user_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCreateResponse) ProtoMessage() {}

func (x *UserCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCreateResponse.ProtoReflect.Descriptor instead.
func (*UserCreateResponse) Descriptor() ([]byte, []int) {
	return file_user_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *UserCreateResponse) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_user_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_user_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NickName      string                 `protobuf:"bytes,1,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`
	Role          int32                  `protobuf:"varint,3,opt,name=role,proto3" json:"role,omitempty"`
	Avator        string                 `protobuf:"bytes,4,opt,name=avator,proto3" json:"avator,omitempty"`
	Abstract      string                 `protobuf:"bytes,5,opt,name=abstract,proto3" json:"abstract,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_user_rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_user_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserResponse) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *GetUserResponse) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *GetUserResponse) GetAvator() string {
	if x != nil {
		return x.Avator
	}
	return ""
}

func (x *GetUserResponse) GetAbstract() string {
	if x != nil {
		return x.Abstract
	}
	return ""
}

type GetUserBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []uint64               `protobuf:"varint,1,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserBatchRequest) Reset() {
	*x = GetUserBatchRequest{}
	mi := &file_user_rpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBatchRequest) ProtoMessage() {}

func (x *GetUserBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBatchRequest.ProtoReflect.Descriptor instead.
func (*GetUserBatchRequest) Descriptor() ([]byte, []int) {
	return file_user_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserBatchRequest) GetUserIds() []uint64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type GetUserBatchResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Users         map[uint64]*GetUserResponse `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserBatchResponse) Reset() {
	*x = GetUserBatchResponse{}
	mi := &file_user_rpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBatchResponse) ProtoMessage() {}

func (x *GetUserBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBatchResponse.ProtoReflect.Descriptor instead.
func (*GetUserBatchResponse) Descriptor() ([]byte, []int) {
	return file_user_rpc_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserBatchResponse) GetUsers() map[uint64]*GetUserResponse {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_user_rpc_proto protoreflect.FileDescriptor

const file_user_rpc_proto_rawDesc = "" +
	"\n" +
	"\x0euser_rpc.proto\x12\buser_rpc\"\x91\x01\n" +
	"\x11UserCreateRequest\x12\x1b\n" +
	"\tnick_name\x18\x01 \x01(\tR\bnickName\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x12\n" +
	"\x04role\x18\x03 \x01(\x05R\x04role\x12\x16\n" +
	"\x06avator\x18\x04 \x01(\tR\x06avator\x12\x17\n" +
	"\aopen_id\x18\x05 \x01(\tR\x06openId\"-\n" +
	"\x12UserCreateResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"v\n" +
	"\x0fGetUserResponse\x12\x1b\n" +
	"\tnick_name\x18\x01 \x01(\tR\bnickName\x12\x12\n" +
	"\x04role\x18\x03 \x01(\x05R\x04role\x12\x16\n" +
	"\x06avator\x18\x04 \x01(\tR\x06avator\x12\x1a\n" +
	"\babstract\x18\x05 \x01(\tR\babstract\"0\n" +
	"\x13GetUserBatchRequest\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\x04R\auserIds\"\xac\x01\n" +
	"\x14GetUserBatchResponse\x12?\n" +
	"\x05users\x18\x01 \x03(\v2).user_rpc.GetUserBatchResponse.UsersEntryR\x05users\x1aS\n" +
	"\n" +
	"UsersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.user_rpc.GetUserResponseR\x05value:\x028\x012\xde\x01\n" +
	"\x04User\x12G\n" +
	"\n" +
	"CreateUser\x12\x1b.user_rpc.UserCreateRequest\x1a\x1c.user_rpc.UserCreateResponse\x12>\n" +
	"\aGetUser\x12\x18.user_rpc.GetUserRequest\x1a\x19.user_rpc.GetUserResponse\x12M\n" +
	"\fGetUserBatch\x12\x1d.user_rpc.GetUserBatchRequest\x1a\x1e.user_rpc.GetUserBatchResponseB\fZ\n" +
	"./user_rpcb\x06proto3"

var (
	file_user_rpc_proto_rawDescOnce sync.Once
	file_user_rpc_proto_rawDescData []byte
)

func file_user_rpc_proto_rawDescGZIP() []byte {
	file_user_rpc_proto_rawDescOnce.Do(func() {
		file_user_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_rpc_proto_rawDesc), len(file_user_rpc_proto_rawDesc)))
	})
	return file_user_rpc_proto_rawDescData
}

var file_user_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_user_rpc_proto_goTypes = []any{
	(*UserCreateRequest)(nil),    // 0: user_rpc.UserCreateRequest
	(*UserCreateResponse)(nil),   // 1: user_rpc.UserCreateResponse
	(*GetUserRequest)(nil),       // 2: user_rpc.GetUserRequest
	(*GetUserResponse)(nil),      // 3: user_rpc.GetUserResponse
	(*GetUserBatchRequest)(nil),  // 4: user_rpc.GetUserBatchRequest
	(*GetUserBatchResponse)(nil), // 5: user_rpc.GetUserBatchResponse
	nil,                          // 6: user_rpc.GetUserBatchResponse.UsersEntry
}
var file_user_rpc_proto_depIdxs = []int32{
	6, // 0: user_rpc.GetUserBatchResponse.users:type_name -> user_rpc.GetUserBatchResponse.UsersEntry
	3, // 1: user_rpc.GetUserBatchResponse.UsersEntry.value:type_name -> user_rpc.GetUserResponse
	0, // 2: user_rpc.User.CreateUser:input_type -> user_rpc.UserCreateRequest
	2, // 3: user_rpc.User.GetUser:input_type -> user_rpc.GetUserRequest
	4, // 4: user_rpc.User.GetUserBatch:input_type -> user_rpc.GetUserBatchRequest
	1, // 5: user_rpc.User.CreateUser:output_type -> user_rpc.UserCreateResponse
	3, // 6: user_rpc.User.GetUser:output_type -> user_rpc.GetUserResponse
	5, // 7: user_rpc.User.GetUserBatch:output_type -> user_rpc.GetUserBatchResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_user_rpc_proto_init() }
func file_user_rpc_proto_init() {
	if File_user_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_rpc_proto_rawDesc), len(file_user_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_rpc_proto_goTypes,
		DependencyIndexes: file_user_rpc_proto_depIdxs,
		MessageInfos:      file_user_rpc_proto_msgTypes,
	}.Build()
	File_user_rpc_proto = out.File
	file_user_rpc_proto_goTypes = nil
	file_user_rpc_proto_depIdxs = nil
}
