// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user_rpc.proto

package server

import (
	"context"

	"im-server/im_user/user_rpc/internal/logic"
	"im-server/im_user/user_rpc/internal/svc"
	"im-server/im_user/user_rpc/types/user_rpc"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user_rpc.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) CreateUser(ctx context.Context, in *user_rpc.UserCreateRequest) (*user_rpc.UserCreateResponse, error) {
	l := logic.NewCreateUserLogic(ctx, s.svcCtx)
	return l.CreateUser(in)
}

func (s *UserServer) GetUser(ctx context.Context, in *user_rpc.GetUserRequest) (*user_rpc.GetUserResponse, error) {
	l := logic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}

func (s *UserServer) GetUserBatch(ctx context.Context, in *user_rpc.GetUserBatchRequest) (*user_rpc.GetUserBatchResponse, error) {
	l := logic.NewGetUserBatchLogic(ctx, s.svcCtx)
	return l.GetUserBatch(in)
}
