// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type Response struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
	Data string `json:"data"`
}


type ChatHistoryRequest struct {
	UserId uint `header:"uid"`
	Page   int  `form:"page"`
	Limit  int  `form:"limit"`
}

type ChatHistoryResponse struct {
	ID        uint   `json:"id"`
	UserID    uint   `json:"user_id"`
	Avatar    string `json:"avatar"`
	Nickname  string `json:"nickname"`
	CreatedAt string `json:"created_at"`
}

type OnLineRequest struct {
	Token uint `json:"token"`
}

type OnLineResponse struct {
	Status bool `json:"status"`
}
