// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type ChatHistoryRequest struct {
	UserId   uint `header:"uid"`
	Page     int  `form:"page"`
	Limit    int  `form:"limit"`
	FriendId uint `friend_id:"limit"`
}

type ChatHistoryResponse struct {
	ID        uint   `json:"id"`
	UserID    uint   `json:"user_id"`
	Avatar    string `json:"avatar"`
	Nickname  string `json:"nickname"`
	CreatedAt string `json:"created_at"`
}

type ChatSessionRequest struct {
	UserId uint `header:"uid"`
	Page   int  `form:"page"`
	Limit  int  `form:"limit"`
	Key    int  `form:"key"`
}

type ChatSessionResponse struct {
	UserID     uint   `json:"user_id"`
	Avatar     string `json:"avatar"`
	Nickname   string `json:"nickname"`
	CreatedAt  string `json:"created_at"`  //消息时间
	MsgPreview string `json:"msg_preview"` //消息预览
}

type GroupSessionRequest struct {
	UserId uint `header:"uid"`
	Page   int  `form:"page"`
	Limit  int  `form:"limit"`
}

type GroupSessionResponse struct {
	UserID    uint   `json:"user_id"`
	Avatar    string `json:"avatar"`
	Nickname  string `json:"nickname"`
	CreatedAt string `json:"created_at"`
}

type OnLineRequest struct {
	Token string `form:"token"`
}

type OnLineResponse struct {
	Status bool `json:"status"`
}

type Response struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
	Data string `json:"data"`
}
