// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"im-server/im_user/user_api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/user/apply_friend",
				Handler: applyFriendHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/user/friend_apply_list",
				Handler: friendApplyListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/user/friend_info",
				Handler: FriendInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/user/friend_list",
				Handler: FriendListHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/user/friends",
				Handler: friendDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/user/response_friend_apply",
				Handler: responseFriendApplyHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/user/update_user_info",
				Handler: UpdateUserInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/user/user_info",
				Handler: UserInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/user/user_search",
				Handler: UserSearchHandler(serverCtx),
			},
		},
	)
}
